[package]
name = "mrget/magiccombatroblox"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

ByteNetMax = "elitriare/bytenet-max@1.0.0"
Component = "sleitnick/component@2.4.8"
Signal = "sleitnick/signal@2.0.3"
Trove = "sleitnick/trove@1.3.0"
Loader = "sleitnick/loader@2.0.0"
TableUtil = "sleitnick/table-util@1.2.1"
Promise = "evaera/promise@4.0.0"